# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/developer/github/torrc_util/torrc_util

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/developer/github/torrc_util/torrc_util

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/developer/github/torrc_util/torrc_util/CMakeFiles /home/developer/github/torrc_util/torrc_util/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/developer/github/torrc_util/torrc_util/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named torrc_util

# Build rule for target.
torrc_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 torrc_util
.PHONY : torrc_util

# fast build rule for target.
torrc_util/fast:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/build
.PHONY : torrc_util/fast

#=============================================================================
# Target rules for targets named torrc_util_automoc

# Build rule for target.
torrc_util_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 torrc_util_automoc
.PHONY : torrc_util_automoc

# fast build rule for target.
torrc_util_automoc/fast:
	$(MAKE) -f CMakeFiles/torrc_util_automoc.dir/build.make CMakeFiles/torrc_util_automoc.dir/build
.PHONY : torrc_util_automoc/fast

qrc_gui_resources.o: qrc_gui_resources.cpp.o

.PHONY : qrc_gui_resources.o

# target to build an object file
qrc_gui_resources.cpp.o:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/qrc_gui_resources.cpp.o
.PHONY : qrc_gui_resources.cpp.o

qrc_gui_resources.i: qrc_gui_resources.cpp.i

.PHONY : qrc_gui_resources.i

# target to preprocess a source file
qrc_gui_resources.cpp.i:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/qrc_gui_resources.cpp.i
.PHONY : qrc_gui_resources.cpp.i

qrc_gui_resources.s: qrc_gui_resources.cpp.s

.PHONY : qrc_gui_resources.s

# target to generate assembly for a file
qrc_gui_resources.cpp.s:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/qrc_gui_resources.cpp.s
.PHONY : qrc_gui_resources.cpp.s

src/coordinator.o: src/coordinator.cpp.o

.PHONY : src/coordinator.o

# target to build an object file
src/coordinator.cpp.o:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/coordinator.cpp.o
.PHONY : src/coordinator.cpp.o

src/coordinator.i: src/coordinator.cpp.i

.PHONY : src/coordinator.i

# target to preprocess a source file
src/coordinator.cpp.i:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/coordinator.cpp.i
.PHONY : src/coordinator.cpp.i

src/coordinator.s: src/coordinator.cpp.s

.PHONY : src/coordinator.s

# target to generate assembly for a file
src/coordinator.cpp.s:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/coordinator.cpp.s
.PHONY : src/coordinator.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainwindow.o: src/mainwindow.cpp.o

.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/mainwindow.cpp.o
.PHONY : src/mainwindow.cpp.o

src/mainwindow.i: src/mainwindow.cpp.i

.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s

.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/node_lookup.o: src/node_lookup.cpp.o

.PHONY : src/node_lookup.o

# target to build an object file
src/node_lookup.cpp.o:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/node_lookup.cpp.o
.PHONY : src/node_lookup.cpp.o

src/node_lookup.i: src/node_lookup.cpp.i

.PHONY : src/node_lookup.i

# target to preprocess a source file
src/node_lookup.cpp.i:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/node_lookup.cpp.i
.PHONY : src/node_lookup.cpp.i

src/node_lookup.s: src/node_lookup.cpp.s

.PHONY : src/node_lookup.s

# target to generate assembly for a file
src/node_lookup.cpp.s:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/node_lookup.cpp.s
.PHONY : src/node_lookup.cpp.s

src/tor_config_options.o: src/tor_config_options.cpp.o

.PHONY : src/tor_config_options.o

# target to build an object file
src/tor_config_options.cpp.o:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/tor_config_options.cpp.o
.PHONY : src/tor_config_options.cpp.o

src/tor_config_options.i: src/tor_config_options.cpp.i

.PHONY : src/tor_config_options.i

# target to preprocess a source file
src/tor_config_options.cpp.i:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/tor_config_options.cpp.i
.PHONY : src/tor_config_options.cpp.i

src/tor_config_options.s: src/tor_config_options.cpp.s

.PHONY : src/tor_config_options.s

# target to generate assembly for a file
src/tor_config_options.cpp.s:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/tor_config_options.cpp.s
.PHONY : src/tor_config_options.cpp.s

src/tor_options_dialog.o: src/tor_options_dialog.cpp.o

.PHONY : src/tor_options_dialog.o

# target to build an object file
src/tor_options_dialog.cpp.o:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/tor_options_dialog.cpp.o
.PHONY : src/tor_options_dialog.cpp.o

src/tor_options_dialog.i: src/tor_options_dialog.cpp.i

.PHONY : src/tor_options_dialog.i

# target to preprocess a source file
src/tor_options_dialog.cpp.i:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/tor_options_dialog.cpp.i
.PHONY : src/tor_options_dialog.cpp.i

src/tor_options_dialog.s: src/tor_options_dialog.cpp.s

.PHONY : src/tor_options_dialog.s

# target to generate assembly for a file
src/tor_options_dialog.cpp.s:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/tor_options_dialog.cpp.s
.PHONY : src/tor_options_dialog.cpp.s

src/tor_options_dialog_factory.o: src/tor_options_dialog_factory.cpp.o

.PHONY : src/tor_options_dialog_factory.o

# target to build an object file
src/tor_options_dialog_factory.cpp.o:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/tor_options_dialog_factory.cpp.o
.PHONY : src/tor_options_dialog_factory.cpp.o

src/tor_options_dialog_factory.i: src/tor_options_dialog_factory.cpp.i

.PHONY : src/tor_options_dialog_factory.i

# target to preprocess a source file
src/tor_options_dialog_factory.cpp.i:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/tor_options_dialog_factory.cpp.i
.PHONY : src/tor_options_dialog_factory.cpp.i

src/tor_options_dialog_factory.s: src/tor_options_dialog_factory.cpp.s

.PHONY : src/tor_options_dialog_factory.s

# target to generate assembly for a file
src/tor_options_dialog_factory.cpp.s:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/tor_options_dialog_factory.cpp.s
.PHONY : src/tor_options_dialog_factory.cpp.s

src/tor_options_factory.o: src/tor_options_factory.cpp.o

.PHONY : src/tor_options_factory.o

# target to build an object file
src/tor_options_factory.cpp.o:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/tor_options_factory.cpp.o
.PHONY : src/tor_options_factory.cpp.o

src/tor_options_factory.i: src/tor_options_factory.cpp.i

.PHONY : src/tor_options_factory.i

# target to preprocess a source file
src/tor_options_factory.cpp.i:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/tor_options_factory.cpp.i
.PHONY : src/tor_options_factory.cpp.i

src/tor_options_factory.s: src/tor_options_factory.cpp.s

.PHONY : src/tor_options_factory.s

# target to generate assembly for a file
src/tor_options_factory.cpp.s:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/src/tor_options_factory.cpp.s
.PHONY : src/tor_options_factory.cpp.s

torrc_util_automoc.o: torrc_util_automoc.cpp.o

.PHONY : torrc_util_automoc.o

# target to build an object file
torrc_util_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/torrc_util_automoc.cpp.o
.PHONY : torrc_util_automoc.cpp.o

torrc_util_automoc.i: torrc_util_automoc.cpp.i

.PHONY : torrc_util_automoc.i

# target to preprocess a source file
torrc_util_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/torrc_util_automoc.cpp.i
.PHONY : torrc_util_automoc.cpp.i

torrc_util_automoc.s: torrc_util_automoc.cpp.s

.PHONY : torrc_util_automoc.s

# target to generate assembly for a file
torrc_util_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/torrc_util.dir/build.make CMakeFiles/torrc_util.dir/torrc_util_automoc.cpp.s
.PHONY : torrc_util_automoc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... torrc_util"
	@echo "... torrc_util_automoc"
	@echo "... qrc_gui_resources.o"
	@echo "... qrc_gui_resources.i"
	@echo "... qrc_gui_resources.s"
	@echo "... src/coordinator.o"
	@echo "... src/coordinator.i"
	@echo "... src/coordinator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... src/node_lookup.o"
	@echo "... src/node_lookup.i"
	@echo "... src/node_lookup.s"
	@echo "... src/tor_config_options.o"
	@echo "... src/tor_config_options.i"
	@echo "... src/tor_config_options.s"
	@echo "... src/tor_options_dialog.o"
	@echo "... src/tor_options_dialog.i"
	@echo "... src/tor_options_dialog.s"
	@echo "... src/tor_options_dialog_factory.o"
	@echo "... src/tor_options_dialog_factory.i"
	@echo "... src/tor_options_dialog_factory.s"
	@echo "... src/tor_options_factory.o"
	@echo "... src/tor_options_factory.i"
	@echo "... src/tor_options_factory.s"
	@echo "... torrc_util_automoc.o"
	@echo "... torrc_util_automoc.i"
	@echo "... torrc_util_automoc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

